### ISSUE TITLE
rpcChannel callmethod问题

### ISSUE THREAD

**Issue by EchoUtopia** [nightfade/protobuf-RPC#1]
之前看你博客教程学习protobuf rpc实现，感觉很不错。
有个疑问，rpcchannel和service都有个callmethod，rpcchannel自己实现的，service不需要自己实现，现成的。我的理解是，rpcchannel在stub执行service定义的方法的时候就自动调用rpcchannel的callmethod，然后发送数据。service的callmethod会根据descriptor等来决定调用serivce定义的哪个方法。请问我的理解对么？

**Comment by nightfade** [comment]
是这样的：）

**Comment by EchoUtopia** [comment]
回复好快，之前没接触过rpc，什么service、channel、stub一脸懵逼，看了你的博文了解了很多，谢谢啦
